#!/usr/bin/env bash
# The herdr package must survive Herdr and plugin upgrades: only user-authored
# files may be tracked, and reapplying the package must not conflict.
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
TMPDIR="$(mktemp -d)"
export HOME="$TMPDIR/home"
trap 'rm -rf "$TMPDIR"' EXIT

command -v stow >/dev/null || { printf 'FAIL: stow not found\n' >&2; exit 1; }

fail() { printf 'FAIL: %s\n' "$*" >&2; exit 1; }

stow_herdr() { stow --dir="$ROOT_DIR" --target="$HOME" herdr; }

CONFIG_REL=".config/herdr/plugins/config/beyondlex.herdr-recent-navigator/config.toml"
PLUGIN_CONFIG="$HOME/$CONFIG_REL"
SOURCE="$ROOT_DIR/herdr/$CONFIG_REL"

# Mirror the real home: the plugin config directory already exists as a real
# directory, so Stow links the tracked file instead of folding the tree.
mkdir -p "$(dirname "$PLUGIN_CONFIG")"

stow_herdr

[[ -L "$PLUGIN_CONFIG" ]] || fail "$CONFIG_REL should be a Stow symlink"
[[ "$(readlink -f "$PLUGIN_CONFIG")" == "$SOURCE" ]] ||
	fail "$CONFIG_REL does not resolve to the repo copy"
grep -q 'move_up = \["Up", "C-k"\]' "$PLUGIN_CONFIG" || fail "move_up binding missing"
grep -q 'move_down = \["Down", "C-j"\]' "$PLUGIN_CONFIG" || fail "move_down binding missing"

# Regenerated by Herdr and the plugin installer; tracking them only caused
# conflicts on every upgrade.
[[ ! -e "$HOME/.config/herdr/.plugins.lock" ]] || fail ".plugins.lock must not be stowed"
[[ ! -e "$HOME/.local/share/herdr-recent-navigator/herdr-plugin.toml" ]] ||
	fail "plugin manifest must not be stowed"

# Reapplying must be a no-op, not a conflict.
stow_herdr

# Recovery path documented in README.md: an upgrade can replace the link with a
# seeded template file.
rm "$PLUGIN_CONFIG"
printf 'template without bindings\n' >"$PLUGIN_CONFIG"
rm "$PLUGIN_CONFIG"
stow_herdr
[[ -L "$PLUGIN_CONFIG" ]] || fail "recovery did not restore the symlink"
grep -q 'move_down = \["Down", "C-j"\]' "$PLUGIN_CONFIG" || fail "recovery lost the bindings"

printf 'herdr stow package: ok\n'
