#!/usr/bin/env bash
# The herdr package must survive Herdr and plugin upgrades: only user-authored
# files may be tracked, and reapplying the package must not conflict.
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
TMPDIR="$(mktemp -d)"
export HOME="$TMPDIR/home"
trap 'rm -rf "$TMPDIR"' EXIT

STOW_DIR="$TMPDIR/stow"
mkdir -p "$STOW_DIR"
cp -R "$ROOT_DIR/herdr" "$STOW_DIR/"

# A running Herdr writes these files into a folded checkout. The package must
# ignore them rather than trying to stow runtime state and socket symlinks.
RUNTIME_ROOT="$STOW_DIR/herdr/.config/herdr"
touch "$RUNTIME_ROOT/.plugins.lock" \
	"$RUNTIME_ROOT/focus-state.json" \
	"$RUNTIME_ROOT/herdr-client.log" \
	"$RUNTIME_ROOT/herdr-server.log" \
	"$RUNTIME_ROOT/plugins.json" \
	"$RUNTIME_ROOT/release-notes.json" \
	"$RUNTIME_ROOT/session.json"
ln -s /private/tmp/com.apple.launchd.fake/Listeners "$RUNTIME_ROOT/herdr.sock.agent"
mkdir -p "$RUNTIME_ROOT/sessions" "$RUNTIME_ROOT/session-snapshots"
touch "$RUNTIME_ROOT/sessions/current.json" "$RUNTIME_ROOT/session-snapshots/latest.json"
mkdir -p "$STOW_DIR/herdr/.local/share/herdr-recent-navigator"
touch "$STOW_DIR/herdr/.local/share/herdr-recent-navigator/herdr-plugin.toml"

command -v stow >/dev/null || { printf 'FAIL: stow not found\n' >&2; exit 1; }

fail() { printf 'FAIL: %s\n' "$*" >&2; exit 1; }

stow_herdr() { stow --dir="$STOW_DIR" --target="$HOME" herdr; }

CONFIG_REL=".config/herdr/plugins/config/beyondlex.herdr-recent-navigator/config.toml"
PLUGIN_CONFIG="$HOME/$CONFIG_REL"
SOURCE="$STOW_DIR/herdr/$CONFIG_REL"

# Mirror the real home: both runtime directories already exist as real
# directories, so Stow links tracked files instead of folding their trees.
mkdir -p "$(dirname "$PLUGIN_CONFIG")" "$HOME/.local/share/herdr-recent-navigator"

stow_herdr

[[ -L "$PLUGIN_CONFIG" ]] || fail "$CONFIG_REL should be a Stow symlink"
[[ "$(readlink -f "$PLUGIN_CONFIG")" == "$(readlink -f "$SOURCE")" ]] ||
	fail "$CONFIG_REL does not resolve to the repo copy"
grep -q 'move_up = \["Up", "C-k"\]' "$PLUGIN_CONFIG" || fail "move_up binding missing"
grep -q 'move_down = \["Down", "C-j"\]' "$PLUGIN_CONFIG" || fail "move_down binding missing"

# Regenerated by Herdr and the plugin installer; tracking them only caused
# conflicts on every upgrade.
for runtime_path in \
	.config/herdr/.plugins.lock \
	.config/herdr/focus-state.json \
	.config/herdr/herdr-client.log \
	.config/herdr/herdr-server.log \
	.config/herdr/herdr.sock.agent \
	.config/herdr/plugins.json \
	.config/herdr/release-notes.json \
	.config/herdr/session.json \
	.config/herdr/sessions \
	.config/herdr/session-snapshots; do
	[[ ! -e "$HOME/$runtime_path" && ! -L "$HOME/$runtime_path" ]] ||
	fail "$runtime_path must not be stowed"
done
[[ ! -e "$HOME/.local/share/herdr-recent-navigator/herdr-plugin.toml" &&
	! -L "$HOME/.local/share/herdr-recent-navigator/herdr-plugin.toml" ]] ||
	fail "plugin manifest must not be stowed"

# Reapplying must be a no-op, not a conflict.
stow_herdr

# Recovery path documented in README.md: an upgrade can replace the link with a
# seeded template file.
rm "$PLUGIN_CONFIG"
printf 'template without bindings\n' >"$PLUGIN_CONFIG"
rm "$PLUGIN_CONFIG"
stow_herdr
[[ -L "$PLUGIN_CONFIG" ]] || fail "recovery did not restore the symlink"
grep -q 'move_down = \["Down", "C-j"\]' "$PLUGIN_CONFIG" || fail "recovery lost the bindings"

printf 'herdr stow package: ok\n'
